package com.acmecorp.orders

/**
 * Generated by Bean Copy Companion from Order to OrderDto --
 * 2 field(s) mapped, 0 left as TODOs below.
 * Do not hand-edit; regenerate instead.
 */
fun Order.toOrderDto(): OrderDto {
    val target = OrderDto(
        this.getId(),
        "", // TODO(bean-copy): no source value for constructor param 'customer' (String)
        this.getTotal()
    )
    return target
}
